name: CI/CD Pipeline for Construction Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/construction-website:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/construction-website:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/construction-website:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/construction-website:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/construction-website:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH to Server and Pull Latest Image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop construction-website || true
            docker rm construction-website || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/construction-website:latest
            docker run -d --name construction-website -p 80:80 ${{ secrets.DOCKER_USERNAME }}/construction-website:latest
